
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: assignEaseDB
      POSTGRES_USER: lakshita
      POSTGRES_PASSWORD: psqlAssignEasePwd 
      POSTGRES_HOST: localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    image: jainlakshita/assignease-frontend
    container_name: django_container
    command: daphne -b 0.0.0.0 -p 8000 server.asgi:application

    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: bun_container
    image: jainlakshita/assignease-server
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"

    command: bun run dev --host 0.0.0.0
    depends_on:
      - server
      - postgres

volumes:
  postgres_data:





