# Generated by Django 5.1.1 on 2024-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='attachments',
            field=models.FileField(null=True, upload_to='assignment_attachments/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
