# Generated by Django 5.1.1 on 2024-09-19 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='students_id',
        ),
       migrations.RemoveField(
            model_name='channels',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='channels',
            name='channelid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='memberid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    
       
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.FileField(upload_to='assignment_submissions/')),
                ('status', models.CharField(choices=[('1', 'NOT STARTED'), ('2', 'UNDER ITERATIONS'), ('3', 'COMPLETED')], default=1)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('iteration_number', models.IntegerField(default=1)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='submit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.submission'),
        ),
        migrations.DeleteModel(
            name='Group_submission',
        ),
    ]
