# Generated by Django 5.1.1 on 2024-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_member_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('1', 'NOT STARTED'), ('2', 'UNDER ITERATIONS'), ('3', 'COMPLETED')], default=1),
        ),
        migrations.AlterField(
            model_name='channels',
            name='channelName',
            field=models.CharField(unique=True),
        ),
    ]
