# Generated by Django 5.1.1 on 2024-10-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_submission_status_group_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='task_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='Attachment_text',
            field=models.TextField(default='no attachments'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.assignments'),
            preserve_default=False,
        ),
    ]
