# Generated by Django 5.1.1 on 2024-10-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_submission_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='Attachment_text',
            field=models.TextField(),
        ),
    ]
