# Generated by Django 5.1.1 on 2024-10-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_submission_attachment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='Attachment_text',
            new_name='submission',
        ),
    ]
