# Generated by Django 5.1.1 on 2024-10-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_attachment_text_submission_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='iteration_number',
        ),
    ]
