# Generated by Django 5.1.1 on 2024-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_submission_iteration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission',
            new_name='submission_text',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment-attachments/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('1', 'NOT STARTED'), ('2', 'NOT REVIEWED'), ('3', 'RESUBMIT'), ('3', 'COMPLETED')], default=1),
        ),
    ]
