# Generated by Django 5.1.1 on 2024-10-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_submission_submission_submission_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('1', 'NOT STARTED'), ('2', 'UNDER ITERATIONS'), ('3', 'COMPLETED')], default=1),
        ),
    ]
