# Generated by Django 5.1.1 on 2024-10-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_submission_submission_submission_text_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('student_id', 'assignment_id'), name='assignedStudnets'),
        ),
    ]
