# Generated by Django 5.1.1 on 2024-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='attachments',
            field=models.FileField(null=True, upload_to='assignments/'),
        ),
    ]
